package TT2018B003.comp3.API.TestCrypto;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import TT2018B003.comp3.API.Service.CryptoService;

@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest
public class CryptoServiceTest {

	@Autowired
	CryptoService cryptoService;
	
	@Test
	@Ignore
	public void decryptTest() {
		String encryptedMessage = "vjPb9kR2lz0/EF0Fp09fQoG+lfJsWXOAnQ+31YE2niSB+e1xijfTFxb2gCUNGHI3vqRe3hd2lK0qyEz9sjlG6dSSEZBHhvhb+ZZmqKRGhDzKa1wf/QF/yTifX0v+AQ4Ba9Fl64c32pmN1xfkSTwe4+vtrD7FAHf7E/PALT2jJn3ipPskCVAn49PbDtSRZbBsqy5b1lWo1yMDLyDVBqqavhmCezfOarEyslLzan4SEZU6DBmHoxEIarL6ybxdqAtdlATB1SzLR5DlE0JTRHLl7lkUlWGa7rDRKBVR2E6iN+wi6zA9b4hfNgM8i+x+xCsN0r/gSPctNbW296WItLh2gg==";
		String decryptedMessage = cryptoService.decryptAESKey(encryptedMessage);
		
		Assert.assertEquals("zapatito12345678", decryptedMessage);
	}
	
	@Test
	@Ignore
	public void decryptPattern() {
		String aesKey = "chialevaledor";
		String encryptedPattern = "U2FsdGVkX18zPrcPTwQRm5nFri/7CVwGKz9F2Kvj4GM=";
		
		String pattern = cryptoService.decryptPattern(encryptedPattern, aesKey);
		
		Assert.assertEquals("hola mundo", pattern);
	}
	
	@Test
	public void doShaTest() {
		String message = "MIIFnDCCBISgAwIBAgIUEpexe331o4hlTIhkyZ7pbX02rqcwDQYJKoZIhvcNAQELBQAwggELMQswCQYDVQQGEwJNWDEZMBcGA1UECAwQQ2l1ZGFkIGRlIE1leGljbzEZMBcGA1UEBwwQR3VzdGF2byBBLk1hZGVybzEOMAwGA1UEEQwFMDc2MDAxLDAqBgNVBAkMI0NhbGxlIDQgTm8uMTIgQ29sLlByb2dyZXNvIE5hY2lvbmFsMRMwEQYDVQQKDApJbmRlZmluaWRvMRMwEQYDVQQLDApJbmRlZmluaWRvMRcwFQYDVQQDDA5pbmRlZmluaWRvLmNvbTEbMBkGA1UEAwwSd3d3LmluZGVmaW5pZG8uY29tMSgwJgYJKoZIhvcNAQkBFhlkaWVnb2FydHVybzIxMjFAZ21haWwuY29tMB4XDTE5MTAwMzA0MDQ0OFoXDTIwMTAwMjA0MDQ0OFowggELMQswCQYDVQQGEwJNWDEZMBcGA1UECAwQQ2l1ZGFkIGRlIE1leGljbzEZMBcGA1UEBwwQR3VzdGF2byBBLk1hZGVybzEOMAwGA1UEEQwFMDc2MDAxLDAqBgNVBAkMI0NhbGxlIDQgTm8uMTIgQ29sLlByb2dyZXNvIE5hY2lvbmFsMRMwEQYDVQQKDApJbmRlZmluaWRvMRMwEQYDVQQLDApJbmRlZmluaWRvMRcwFQYDVQQDDA5pbmRlZmluaWRvLmNvbTEbMBkGA1UEAwwSd3d3LmluZGVmaW5pZG8uY29tMSgwJgYJKoZIhvcNAQkBFhlkaWVnb2FydHVybzIxMjFAZ21haWwuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqAXrx5M+c1LP62aXEIJrq9WSlrRb0hb6iE9kHoGQMEyX9kdDAQsvjcHW1JkNMBb15aFukwpgJpgFIBtSknlspOi3gg0HWub9DxI2BMCFRJL214MJEoU99mul7CGGGN8l7WpDAL3hKSkTQo7GmtMKs0RxUtJUAicrF4CuBEm8x16V9uCxB+12c4wKIULeanfdWBc4Vty0DzBle+uzeyCofjJ+/jq/kwtI33NSIvsxNKMa1YrdYs/ThwbL9IrmuLgMKc/VJ5r8LPOTrad1jKl+prIGbd7CBRWmkPrUiJVa5PmEMWvTOKraAz2bakMbfm5Hz/ESKWwVq+10YNEJxK+WhQIDAQABo4HzMIHwMB0GA1UdDgQWBBS3cixDjZSxB0ZYx0EAAX4U5ymgTDAfBgNVHSMEGDAWgBS3cixDjZSxB0ZYx0EAAX4U5ymgTDARBggrBgEFBQcBGAQFMAMCAQUwEgYDVR0TAQH/BAgwBgEB/wIBATAOBgNVHQ8BAf8EBAMCBaAwSAYDVR0lAQH/BD4wPAYIKwYBBQUHAwEGCCsGAQUFBwMCBggrBgEFBQcDEQYIKwYBBQUHAwcGCCsGAQUFBwMGBggrBgEFBQcDBTAtBgNVHREEJjAkgg5pbmRlZmluaWRvLmNvbYISd3d3LmluZGVmaW5pZG8uY29tMA0GCSqGSIb3DQEBCwUAA4IBAQB+K5I63vEOhRsZS1s1pvjdlttvzomzz4rh0FY+iPE6DGTSoPmHXPqta2YpszXoagGFQ0+gOD3fOuiKm4sEfvFxkRfSSFoWrtW0ujUguLTpa0z/D1p4WoNNeGkRruxFiSHERHW6TbauH8csWTGsQoKG6pzdfYZWxcTyu5jHxW1IDDFE1LCDprhHLEY6S0hwMN3hFF0meRKa0NFxFgx8T2THVOGNyWwJS83fpndhvpcuUg6AVTI22fxERW6EqCO5mZh2iFcartBhGoi8grovzNbm+4/ikCL2AGXaDnrw8w8xqT8DeAEIyEBQcfRp3j3UIuKwE28QH18DmgdXgjLGv6qm";
		String sha = cryptoService.doSHA(message);
		
		Assert.assertEquals("56b1a090cc4216d9c064d41e18865737a9a2d5567a9eee097d534cc5e566c90f", sha);
	}
	
}
